using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Cove.Data.Migrations
{
    /// <inheritdoc />
    public partial class AddAudioTextLibrary : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("ALTER TABLE \"files\" ADD COLUMN IF NOT EXISTS \"AudioId\" integer;");
            migrationBuilder.Sql("ALTER TABLE \"files\" ADD COLUMN IF NOT EXISTS \"Channels\" integer;");
            migrationBuilder.Sql("ALTER TABLE \"files\" ADD COLUMN IF NOT EXISTS \"ExcerptText\" text;");
            migrationBuilder.Sql("ALTER TABLE \"files\" ADD COLUMN IF NOT EXISTS \"HasVideoTrack\" boolean DEFAULT false;");
            migrationBuilder.Sql("ALTER TABLE \"files\" ADD COLUMN IF NOT EXISTS \"ImageFile_Format\" text;");
            migrationBuilder.Sql("ALTER TABLE \"files\" ADD COLUMN IF NOT EXISTS \"PageCount\" integer;");
            migrationBuilder.Sql("ALTER TABLE \"files\" ADD COLUMN IF NOT EXISTS \"SampleRate\" integer;");
            migrationBuilder.Sql("ALTER TABLE \"files\" ADD COLUMN IF NOT EXISTS \"TextDocumentId\" integer;");
            migrationBuilder.Sql("ALTER TABLE \"files\" ADD COLUMN IF NOT EXISTS \"TextFile_Format\" text;");
            migrationBuilder.Sql("ALTER TABLE \"files\" ADD COLUMN IF NOT EXISTS \"VideoFile_AudioCodec\" text;");
            migrationBuilder.Sql("ALTER TABLE \"files\" ADD COLUMN IF NOT EXISTS \"VideoFile_BitRate\" bigint;");
            migrationBuilder.Sql("ALTER TABLE \"files\" ADD COLUMN IF NOT EXISTS \"VideoFile_Duration\" double precision;");
            migrationBuilder.Sql("ALTER TABLE \"files\" ADD COLUMN IF NOT EXISTS \"WordCount\" integer;");

            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS audios (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "Title" text NULL,
                    "Code" text NULL,
                    "Details" text NULL,
                    "Organized" boolean NOT NULL DEFAULT false,
                    "StudioId" integer NULL REFERENCES "studios"("Id") ON DELETE SET NULL,
                    "Date" date NULL,
                    "ImageBlobId" text NULL,
                    "TagIds" integer[] NOT NULL DEFAULT '{}'::integer[],
                    "PerformerIds" integer[] NOT NULL DEFAULT '{}'::integer[],
                    "FileCount" integer NOT NULL DEFAULT 0,
                    "MaxDuration" double precision NOT NULL DEFAULT 0,
                    "MaxBitRate" bigint NOT NULL DEFAULT 0,
                    "MaxFileSize" bigint NOT NULL DEFAULT 0,
                    "MaxFileModTime" timestamp with time zone NULL,
                    "MinPath" text NULL,
                    "MaxPath" text NULL,
                    "FileSearchText" text NULL,
                    "HasVideoFiles" boolean NOT NULL DEFAULT false,
                    "CreatedAt" timestamp with time zone NOT NULL DEFAULT timezone('utc', now()),
                    "UpdatedAt" timestamp with time zone NOT NULL DEFAULT timezone('utc', now())
                )
                """);
            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS audio_urls (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "AudioId" integer NOT NULL REFERENCES audios("Id") ON DELETE CASCADE,
                    "Url" text NOT NULL
                )
                """);
            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS audio_tracks (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "AudioId" integer NOT NULL REFERENCES audios("Id") ON DELETE CASCADE,
                    "OrderIndex" integer NOT NULL DEFAULT 0,
                    "Title" text NULL,
                    "StartSec" double precision NOT NULL DEFAULT 0,
                    "EndSec" double precision NULL,
                    "CreatedAt" timestamp with time zone NOT NULL DEFAULT timezone('utc', now()),
                    "UpdatedAt" timestamp with time zone NOT NULL DEFAULT timezone('utc', now())
                )
                """);
            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS audio_tags (
                    "AudioId" integer NOT NULL REFERENCES audios("Id") ON DELETE CASCADE,
                    "TagId" integer NOT NULL REFERENCES tags("Id") ON DELETE CASCADE,
                    PRIMARY KEY ("AudioId", "TagId")
                )
                """);
            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS audio_performers (
                    "AudioId" integer NOT NULL REFERENCES audios("Id") ON DELETE CASCADE,
                    "PerformerId" integer NOT NULL REFERENCES performers("Id") ON DELETE CASCADE,
                    PRIMARY KEY ("AudioId", "PerformerId")
                )
                """);
            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS text_documents (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "Title" text NULL,
                    "Code" text NULL,
                    "Details" text NULL,
                    "Organized" boolean NOT NULL DEFAULT false,
                    "StudioId" integer NULL REFERENCES "studios"("Id") ON DELETE SET NULL,
                    "Date" date NULL,
                    "ImageBlobId" text NULL,
                    "TagIds" integer[] NOT NULL DEFAULT '{}'::integer[],
                    "PerformerIds" integer[] NOT NULL DEFAULT '{}'::integer[],
                    "FileCount" integer NOT NULL DEFAULT 0,
                    "MaxWordCount" integer NULL,
                    "MaxPageCount" integer NULL,
                    "MaxFileSize" bigint NOT NULL DEFAULT 0,
                    "MaxFileModTime" timestamp with time zone NULL,
                    "MinPath" text NULL,
                    "MaxPath" text NULL,
                    "FileSearchText" text NULL,
                    "CreatedAt" timestamp with time zone NOT NULL DEFAULT timezone('utc', now()),
                    "UpdatedAt" timestamp with time zone NOT NULL DEFAULT timezone('utc', now())
                )
                """);
            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS text_urls (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "TextDocumentId" integer NOT NULL REFERENCES text_documents("Id") ON DELETE CASCADE,
                    "Url" text NOT NULL
                )
                """);
            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS text_tags (
                    "TextDocumentId" integer NOT NULL REFERENCES text_documents("Id") ON DELETE CASCADE,
                    "TagId" integer NOT NULL REFERENCES tags("Id") ON DELETE CASCADE,
                    PRIMARY KEY ("TextDocumentId", "TagId")
                )
                """);
            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS text_performers (
                    "TextDocumentId" integer NOT NULL REFERENCES text_documents("Id") ON DELETE CASCADE,
                    "PerformerId" integer NOT NULL REFERENCES performers("Id") ON DELETE CASCADE,
                    PRIMARY KEY ("TextDocumentId", "PerformerId")
                )
                """);

            migrationBuilder.Sql("CREATE INDEX IF NOT EXISTS \"IX_files_AudioId_Path\" ON \"files\" (\"AudioId\", \"Path\");");
            migrationBuilder.Sql("CREATE INDEX IF NOT EXISTS \"IX_files_TextDocumentId_Path\" ON \"files\" (\"TextDocumentId\", \"Path\");");
            migrationBuilder.Sql("CREATE INDEX IF NOT EXISTS \"IX_audio_performers_PerformerId\" ON audio_performers (\"PerformerId\");");
            migrationBuilder.Sql("CREATE INDEX IF NOT EXISTS \"IX_audio_tags_TagId\" ON audio_tags (\"TagId\");");
            migrationBuilder.Sql("CREATE INDEX IF NOT EXISTS \"IX_audio_tracks_AudioId_OrderIndex\" ON audio_tracks (\"AudioId\", \"OrderIndex\");");
            migrationBuilder.Sql("CREATE INDEX IF NOT EXISTS \"IX_audio_urls_AudioId\" ON audio_urls (\"AudioId\");");
            migrationBuilder.Sql("CREATE INDEX IF NOT EXISTS \"IX_audios_CreatedAt\" ON audios (\"CreatedAt\");");
            migrationBuilder.Sql("CREATE INDEX IF NOT EXISTS \"IX_audios_Date\" ON audios (\"Date\");");
            migrationBuilder.Sql("CREATE INDEX IF NOT EXISTS \"IX_audios_MaxDuration\" ON audios (\"MaxDuration\");");
            migrationBuilder.Sql("CREATE INDEX IF NOT EXISTS \"IX_audios_PerformerIds\" ON audios USING gin (\"PerformerIds\");");
            migrationBuilder.Sql("CREATE INDEX IF NOT EXISTS \"IX_audios_StudioId\" ON audios (\"StudioId\");");
            migrationBuilder.Sql("CREATE INDEX IF NOT EXISTS \"IX_audios_TagIds\" ON audios USING gin (\"TagIds\");");
            migrationBuilder.Sql("CREATE INDEX IF NOT EXISTS \"IX_audios_Title\" ON audios (\"Title\");");
            migrationBuilder.Sql("CREATE INDEX IF NOT EXISTS \"IX_audios_UpdatedAt\" ON audios (\"UpdatedAt\");");
            migrationBuilder.Sql("CREATE INDEX IF NOT EXISTS \"IX_text_documents_CreatedAt\" ON text_documents (\"CreatedAt\");");
            migrationBuilder.Sql("CREATE INDEX IF NOT EXISTS \"IX_text_documents_Date\" ON text_documents (\"Date\");");
            migrationBuilder.Sql("CREATE INDEX IF NOT EXISTS \"IX_text_documents_PerformerIds\" ON text_documents USING gin (\"PerformerIds\");");
            migrationBuilder.Sql("CREATE INDEX IF NOT EXISTS \"IX_text_documents_StudioId\" ON text_documents (\"StudioId\");");
            migrationBuilder.Sql("CREATE INDEX IF NOT EXISTS \"IX_text_documents_TagIds\" ON text_documents USING gin (\"TagIds\");");
            migrationBuilder.Sql("CREATE INDEX IF NOT EXISTS \"IX_text_documents_Title\" ON text_documents (\"Title\");");
            migrationBuilder.Sql("CREATE INDEX IF NOT EXISTS \"IX_text_documents_UpdatedAt\" ON text_documents (\"UpdatedAt\");");
            migrationBuilder.Sql("CREATE INDEX IF NOT EXISTS \"IX_text_performers_PerformerId\" ON text_performers (\"PerformerId\");");
            migrationBuilder.Sql("CREATE INDEX IF NOT EXISTS \"IX_text_tags_TagId\" ON text_tags (\"TagId\");");
            migrationBuilder.Sql("CREATE INDEX IF NOT EXISTS \"IX_text_urls_TextDocumentId\" ON text_urls (\"TextDocumentId\");");

            migrationBuilder.Sql("""
                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM pg_constraint
                        WHERE conname = 'FK_files_audios_AudioId'
                            AND conrelid = 'files'::regclass
                    ) THEN
                        ALTER TABLE "files"
                        ADD CONSTRAINT "FK_files_audios_AudioId"
                        FOREIGN KEY ("AudioId") REFERENCES audios("Id") ON DELETE SET NULL;
                    END IF;
                END $$;
                """);
            migrationBuilder.Sql("""
                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM pg_constraint
                        WHERE conname = 'FK_files_text_documents_TextDocumentId'
                            AND conrelid = 'files'::regclass
                    ) THEN
                        ALTER TABLE "files"
                        ADD CONSTRAINT "FK_files_text_documents_TextDocumentId"
                        FOREIGN KEY ("TextDocumentId") REFERENCES text_documents("Id") ON DELETE SET NULL;
                    END IF;
                END $$;
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_files_audios_AudioId",
                table: "files");

            migrationBuilder.DropForeignKey(
                name: "FK_files_text_documents_TextDocumentId",
                table: "files");

            migrationBuilder.DropTable(
                name: "audio_performers");

            migrationBuilder.DropTable(
                name: "audio_tags");

            migrationBuilder.DropTable(
                name: "audio_tracks");

            migrationBuilder.DropTable(
                name: "audio_urls");

            migrationBuilder.DropTable(
                name: "text_performers");

            migrationBuilder.DropTable(
                name: "text_tags");

            migrationBuilder.DropTable(
                name: "text_urls");

            migrationBuilder.DropTable(
                name: "audios");

            migrationBuilder.DropTable(
                name: "text_documents");

            migrationBuilder.DropIndex(
                name: "IX_files_AudioId_Path",
                table: "files");

            migrationBuilder.DropIndex(
                name: "IX_files_TextDocumentId_Path",
                table: "files");

            migrationBuilder.DropColumn(
                name: "AudioId",
                table: "files");

            migrationBuilder.DropColumn(
                name: "Channels",
                table: "files");

            migrationBuilder.DropColumn(
                name: "ExcerptText",
                table: "files");

            migrationBuilder.DropColumn(
                name: "HasVideoTrack",
                table: "files");

            migrationBuilder.DropColumn(
                name: "ImageFile_Format",
                table: "files");

            migrationBuilder.DropColumn(
                name: "PageCount",
                table: "files");

            migrationBuilder.DropColumn(
                name: "SampleRate",
                table: "files");

            migrationBuilder.DropColumn(
                name: "TextDocumentId",
                table: "files");

            migrationBuilder.DropColumn(
                name: "TextFile_Format",
                table: "files");

            migrationBuilder.DropColumn(
                name: "VideoFile_AudioCodec",
                table: "files");

            migrationBuilder.DropColumn(
                name: "VideoFile_BitRate",
                table: "files");

            migrationBuilder.DropColumn(
                name: "VideoFile_Duration",
                table: "files");

            migrationBuilder.DropColumn(
                name: "WordCount",
                table: "files");
        }
    }
}
