using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Cove.Data.Migrations
{
    /// <inheritdoc />
    public partial class AddFieldProvenance : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS "field_provenance" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "HostType" integer NOT NULL,
                    "HostId" integer NOT NULL,
                    "FieldKey" character varying(100) NOT NULL,
                    "ValueJson" jsonb NULL,
                    "SourceKey" text NOT NULL,
                    "SourceRunId" text NOT NULL DEFAULT '',
                    "ModelKey" text NOT NULL DEFAULT '',
                    "Confidence" real NULL,
                    "CreatedAt" timestamp with time zone NOT NULL,
                    "UpdatedAt" timestamp with time zone NOT NULL
                );

                CREATE INDEX IF NOT EXISTS "IX_field_provenance_HostType_HostId" ON "field_provenance" ("HostType", "HostId");
                CREATE INDEX IF NOT EXISTS "IX_field_provenance_HostType_HostId_FieldKey" ON "field_provenance" ("HostType", "HostId", "FieldKey");
                CREATE UNIQUE INDEX IF NOT EXISTS "IX_field_provenance_HostType_HostId_FieldKey_SourceKey_SourceR~" ON "field_provenance" ("HostType", "HostId", "FieldKey", "SourceKey", "SourceRunId", "ModelKey");
                CREATE INDEX IF NOT EXISTS "IX_field_provenance_SourceKey" ON "field_provenance" ("SourceKey");
            """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "field_provenance");
        }
    }
}
