using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Cove.Data.Migrations
{
    /// <inheritdoc />
    public partial class AddNormalizedCustomFields : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                ALTER TABLE IF EXISTS "tags" DROP COLUMN IF EXISTS "CustomFields";
                ALTER TABLE IF EXISTS "studios" DROP COLUMN IF EXISTS "CustomFields";
                ALTER TABLE IF EXISTS "scenes" DROP COLUMN IF EXISTS "CustomFields";
                ALTER TABLE IF EXISTS "performers" DROP COLUMN IF EXISTS "CustomFields";
                ALTER TABLE IF EXISTS "images" DROP COLUMN IF EXISTS "CustomFields";
                ALTER TABLE IF EXISTS "groups" DROP COLUMN IF EXISTS "CustomFields";
                ALTER TABLE IF EXISTS "galleries" DROP COLUMN IF EXISTS "CustomFields";
                ALTER TABLE IF EXISTS "faces" DROP COLUMN IF EXISTS "CustomFields";

                CREATE TABLE IF NOT EXISTS "custom_field_definitions" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "Key" character varying(100) NOT NULL,
                    "Label" character varying(200) NOT NULL,
                    "Type" character varying(50) NOT NULL,
                    "EntityTypes" text[] NOT NULL,
                    "Options" text[] NOT NULL,
                    "Filterable" boolean NOT NULL,
                    "Sortable" boolean NOT NULL,
                    "IsMultiValue" boolean NOT NULL,
                    "DisplayOrder" integer NOT NULL,
                    "CreatedAt" timestamp with time zone NOT NULL,
                    "UpdatedAt" timestamp with time zone NOT NULL
                );

                CREATE TABLE IF NOT EXISTS "custom_field_values" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "DefinitionId" integer NOT NULL REFERENCES "custom_field_definitions"("Id") ON DELETE CASCADE,
                    "EntityType" character varying(50) NOT NULL,
                    "EntityId" integer NOT NULL,
                    "Position" integer NOT NULL,
                    "TextValue" character varying(4000) NULL,
                    "NumberValue" numeric(18,6) NULL,
                    "BoolValue" boolean NULL,
                    "DateValue" date NULL,
                    "TimestampValue" timestamp with time zone NULL,
                    "IntegerValue" integer NULL,
                    "CreatedAt" timestamp with time zone NOT NULL,
                    "UpdatedAt" timestamp with time zone NOT NULL
                );

                CREATE INDEX IF NOT EXISTS "IX_custom_field_definitions_DisplayOrder" ON "custom_field_definitions" ("DisplayOrder");
                CREATE UNIQUE INDEX IF NOT EXISTS "IX_custom_field_definitions_Key" ON "custom_field_definitions" ("Key");
                CREATE INDEX IF NOT EXISTS "IX_custom_field_values_DefinitionId_EntityType_BoolValue" ON "custom_field_values" ("DefinitionId", "EntityType", "BoolValue");
                CREATE INDEX IF NOT EXISTS "IX_custom_field_values_DefinitionId_EntityType_DateValue" ON "custom_field_values" ("DefinitionId", "EntityType", "DateValue");
                CREATE UNIQUE INDEX IF NOT EXISTS "IX_custom_field_values_DefinitionId_EntityType_EntityId_Positi~" ON "custom_field_values" ("DefinitionId", "EntityType", "EntityId", "Position");
                CREATE INDEX IF NOT EXISTS "IX_custom_field_values_DefinitionId_EntityType_IntegerValue" ON "custom_field_values" ("DefinitionId", "EntityType", "IntegerValue");
                CREATE INDEX IF NOT EXISTS "IX_custom_field_values_DefinitionId_EntityType_NumberValue" ON "custom_field_values" ("DefinitionId", "EntityType", "NumberValue");
                CREATE INDEX IF NOT EXISTS "IX_custom_field_values_DefinitionId_EntityType_TextValue" ON "custom_field_values" ("DefinitionId", "EntityType", "TextValue");
                CREATE INDEX IF NOT EXISTS "IX_custom_field_values_DefinitionId_EntityType_TimestampValue" ON "custom_field_values" ("DefinitionId", "EntityType", "TimestampValue");
                CREATE INDEX IF NOT EXISTS "IX_custom_field_values_EntityType_EntityId" ON "custom_field_values" ("EntityType", "EntityId");
            """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "custom_field_values");

            migrationBuilder.DropTable(
                name: "custom_field_definitions");

            migrationBuilder.AddColumn<Dictionary<string, object>>(
                name: "CustomFields",
                table: "tags",
                type: "jsonb",
                nullable: true);

            migrationBuilder.AddColumn<Dictionary<string, object>>(
                name: "CustomFields",
                table: "studios",
                type: "jsonb",
                nullable: true);

            migrationBuilder.AddColumn<Dictionary<string, object>>(
                name: "CustomFields",
                table: "scenes",
                type: "jsonb",
                nullable: true);

            migrationBuilder.AddColumn<Dictionary<string, object>>(
                name: "CustomFields",
                table: "performers",
                type: "jsonb",
                nullable: true);

            migrationBuilder.AddColumn<Dictionary<string, object>>(
                name: "CustomFields",
                table: "images",
                type: "jsonb",
                nullable: true);

            migrationBuilder.AddColumn<Dictionary<string, object>>(
                name: "CustomFields",
                table: "groups",
                type: "jsonb",
                nullable: true);

            migrationBuilder.AddColumn<Dictionary<string, object>>(
                name: "CustomFields",
                table: "galleries",
                type: "jsonb",
                nullable: true);

            migrationBuilder.AddColumn<Dictionary<string, object>>(
                name: "CustomFields",
                table: "faces",
                type: "jsonb",
                nullable: true);
        }
    }
}
